package main

import "strings"

// fallbackExternalPackages is the set of upstream go packages
// whose .proto we import rather than regenerate if a gen from
// target repo fails.
var fallbackExternalPackages = strings.Join([]string{
	"-k8s.io/apimachinery/pkg/util/intstr",
	"-k8s.io/apimachinery/pkg/api/resource",
	"-k8s.io/apimachinery/pkg/runtime/schema",
	"-k8s.io/apimachinery/pkg/runtime",
	"-k8s.io/apimachinery/pkg/apis/meta/v1",
	"-k8s.io/apimachinery/pkg/apis/meta/v1beta1",
	"-k8s.io/apimachinery/pkg/apis/testapigroup/v1",
	// Kubernetes types with already generated protobuf
	"-k8s.io/api/admissionregistration/v1",
	"-k8s.io/api/admissionregistration/v1alpha1",
	"-k8s.io/api/admissionregistration/v1beta1",
	"-k8s.io/api/admission/v1",
	"-k8s.io/api/admission/v1beta1",
	"-k8s.io/api/apidiscovery/v2",
	"-k8s.io/api/apidiscovery/v2beta1",
	"-k8s.io/api/apiserverinternal/v1alpha1",
	"-k8s.io/api/apps/v1",
	"-k8s.io/api/apps/v1beta1",
	"-k8s.io/api/apps/v1beta2",
	"-k8s.io/api/authentication/v1",
	"-k8s.io/api/authentication/v1alpha1",
	"-k8s.io/api/authentication/v1beta1",
	"-k8s.io/api/authorization/v1",
	"-k8s.io/api/authorization/v1beta1",
	"-k8s.io/api/autoscaling/v1",
	"-k8s.io/api/autoscaling/v2",
	"-k8s.io/api/batch/v1",
	"-k8s.io/api/batch/v1beta1",
	"-k8s.io/api/certificates/v1",
	"-k8s.io/api/certificates/v1alpha1",
	"-k8s.io/api/certificates/v1beta1",
	"-k8s.io/api/coordination/v1",
	"-k8s.io/api/coordination/v1alpha2",
	"-k8s.io/api/coordination/v1beta1",
	"-k8s.io/api/core/v1",
	"-k8s.io/api/discovery/v1",
	"-k8s.io/api/discovery/v1beta1",
	"-k8s.io/api/events/v1",
	"-k8s.io/api/events/v1beta1",
	"-k8s.io/api/extensions/v1beta1",
	"-k8s.io/api/flowcontrol/v1",
	"-k8s.io/api/flowcontrol/v1beta1",
	"-k8s.io/api/flowcontrol/v1beta2",
	"-k8s.io/api/flowcontrol/v1beta3",
	"-k8s.io/api/imagepolicy/v1alpha1",
	"-k8s.io/api/networking/v1",
	"-k8s.io/api/networking/v1beta1",
	"-k8s.io/api/node/v1",
	"-k8s.io/api/node/v1alpha1",
	"-k8s.io/api/node/v1beta1",
	"-k8s.io/api/policy/v1",
	"-k8s.io/api/policy/v1beta1",
	"-k8s.io/api/rbac/v1",
	"-k8s.io/api/rbac/v1alpha1",
	"-k8s.io/api/rbac/v1beta1",
	"-k8s.io/api/resource/v1",
	"-k8s.io/api/resource/v1alpha3",
	"-k8s.io/api/resource/v1beta1",
	"-k8s.io/api/resource/v1beta2",
	"-k8s.io/api/scheduling/v1",
	"-k8s.io/api/scheduling/v1alpha3",
	"-k8s.io/api/scheduling/v1beta1",
	"-k8s.io/api/storagemigration/v1beta1",
	"-k8s.io/api/storage/v1",
	"-k8s.io/api/storage/v1alpha1",
	"-k8s.io/api/storage/v1beta1",
}, ",")
